COMPONENT=Testcc2420RadioC

PFLAGS += -I../tos/chips/cc2420/
PFLAGS += -I../tos/chips/cc2420/transmit
PFLAGS += -I../tos/chips/cc2420/priorityMAC
PFLAGS += -I../tos/chips/cc2420/priorityMACQueue
PFLAGS += -I../tos/chips/cc2420/interfaces

PFLAGS += -I$(TOSDIR)/lib/printf
#CFLAGS += -DNEW_PRINTF_SEMANTICS
#CFLAGS +=-DTOSH_DATA_LENGTH=118

include $(MAKERULES)
